// Code generated by "stringer -type Type"; DO NOT EDIT

package scan

import "fmt"

const _Type_name = "EOFErrorNewlineAssignCharGreaterOrEqualIdentifierLeftBraceLeftBrackLeftParenNumberOperatorOpRationalRightBraceRightBrackRightParenSemicolonSpaceString"

var _Type_index = [...]uint8{0, 3, 8, 15, 21, 25, 39, 49, 58, 67, 76, 82, 90, 92, 100, 110, 120, 130, 139, 144}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
